### PR TITLE
Table rotate

### PR DESCRIPTION
**Pull request by molinaro-m**
OK, this is really minor.

For the big table in Section 3 the .tex uses `\begin{landscape} ... \end{landscape}` from the `lscape` package.

The same environment can be used identically from the `pdflscape` that _should_ tell PDF viewers automatically rotate the page view only for that section.

If it works also on your laptops (on mine it does) you might think of adding these minimal 3 characters in the preamble.
Otherwise drop the Pull Request.

### CODE REVIEW

**Comment by molinaro-m** [comment]
Sorry, I built this PR on a branch started from my previous fix branch...I hope it doesn't create confusion.

**Review by mbtaylor — APPROVED** [review]
Thanks Marco, that's a worthwhile usability improvement.  I had a quick go at applying the same change to Table 2, but it affected the formatting a bit, so I backed out of that.

**Comment by Erard** [comment]
I have a 
! LaTeX Error: Missing \begin{document}.
error when I issue make
SOemthing missing on my side?

**Comment by molinaro-m** [comment]
I tried all my local branches and the origin/master (detached) and all of them _make_ without issues...not sure what to suggest here...

**Comment by Erard** [comment]
Sorry, I was mixing different things on my side - this is actually OK.
— Except that the new VOdataService reference seems to be missing

**Comment by molinaro-m** [comment]
I think that's available only in the PR #33 - maybe merging that one first will solve this

**Comment by Erard** [comment]
All clear, thanks

**Pull request merged**
